tasks:
  - name: Server
    init: npm i -g npm redundancyjs; cd UI; npm i --ignore-scripts; npm run build; cd ..; npm i --ignore-scripts; gp sync-done server
    command: npm start
  - name: Angular serve
    init: gp sync-await server
    command: cd UI; npm start
    openMode: split-right
ports:
  - port: 4455
    visibility: public
  - port: 4200
    onOpen: open-browser
    visibility: public
  - port: 8099
    onOpen: ignore
  - port: 5958
    onOpen: ignore
