services:
  tallyarbiter:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        APP_VERSION: "latest"

    container_name: tallyarbiter
    restart: unless-stopped

    ports:
      - "4455:4455"
      - "8099:8099"
      - "5958:5958"

    environment:
      - NODE_ENV=production
      - TZ=America/New_York

    volumes:
      - tallyarbiter-data:/app/data

volumes:
  tallyarbiter-data: