
/*    +-----------------------------------------------------------------------+    */
/*    |    Do not edit this file directly.                                    |    */
/*    |    It was copied by redundancyJS.                                     |    */
/*    |    To modify it, first edit the source file (see redundancy.json).    |    */
/*    |    Then, run "npx redundancyjs" in the terminal.                      |    */
/*    +-----------------------------------------------------------------------+    */

/* do not edit */ export interface BusOption {
/* do not edit */     label: string;
/* do not edit */     type: string;
/* do not edit */ 	id: string;
/* do not edit */     color: string;
/* do not edit */     priority: number;
/* do not edit */ }