
/*    +-----------------------------------------------------------------------+    */
/*    |    Do not edit this file directly.                                    |    */
/*    |    It was copied by redundancyJS.                                     |    */
/*    |    To modify it, first edit the source file (see redundancy.json).    |    */
/*    |    Then, run "npx redundancyjs" in the terminal.                      |    */
/*    +-----------------------------------------------------------------------+    */

/* do not edit */ export interface CloudDestination {
/* do not edit */     connected: boolean;
/* do not edit */     host: string;
/* do not edit */     id: string;
/* do not edit */     key: string;
/* do not edit */     port: string;
/* do not edit */     status: "connected" | "disconnected" | "invalid_key" | "error";
/* do not edit */ }