
/*    +-----------------------------------------------------------------------+    */
/*    |    Do not edit this file directly.                                    |    */
/*    |    It was copied by redundancyJS.                                     |    */
/*    |    To modify it, first edit the source file (see redundancy.json).    |    */
/*    |    Then, run "npx redundancyjs" in the terminal.                      |    */
/*    +-----------------------------------------------------------------------+    */

/* do not edit */ export interface CloudClient {
/* do not edit */     datetimeConnected: number;
/* do not edit */     id: string;
/* do not edit */     inactive: boolean;
/* do not edit */     ipAddress: string;
/* do not edit */     key: string;
/* do not edit */     socketId: string;
/* do not edit */ }