
/*    +-----------------------------------------------------------------------+    */
/*    |    Do not edit this file directly.                                    |    */
/*    |    It was copied by redundancyJS.                                     |    */
/*    |    To modify it, first edit the source file (see redundancy.json).    |    */
/*    |    Then, run "npx redundancyjs" in the terminal.                      |    */
/*    +-----------------------------------------------------------------------+    */

/* do not edit */ interface Source {
/* do not edit */     address: string;
/* do not edit */     sourceId: string;
/* do not edit */ }
/* do not edit */
/* do not edit */ export interface DeviceState {
/* do not edit */     active: boolean;
/* do not edit */     busId: string;
/* do not edit */     deviceId: string;
/* do not edit */     linkedSources: Source[];
/* do not edit */     sources: Source[];
/* do not edit */ }