
/*    +-----------------------------------------------------------------------+    */
/*    |    Do not edit this file directly.                                    |    */
/*    |    It was copied by redundancyJS.                                     |    */
/*    |    To modify it, first edit the source file (see redundancy.json).    |    */
/*    |    Then, run "npx redundancyjs" in the terminal.                      |    */
/*    +-----------------------------------------------------------------------+    */

/* do not edit */ export interface DeviceAction {
/* do not edit */     active: boolean;
/* do not edit */     busId: string;
/* do not edit */     data: Record<string, any>;
/* do not edit */     deviceId: string;
/* do not edit */     id: string;
/* do not edit */     outputTypeId: string;
/* do not edit */     // Volatile
/* do not edit */     outputTypeIdx?: number;
/* do not edit */ }