
/*    +-----------------------------------------------------------------------+    */
/*    |    Do not edit this file directly.                                    |    */
/*    |    It was copied by redundancyJS.                                     |    */
/*    |    To modify it, first edit the source file (see redundancy.json).    |    */
/*    |    Then, run "npx redundancyjs" in the terminal.                      |    */
/*    +-----------------------------------------------------------------------+    */

/* do not edit */ import { Device } from "./Device";
/* do not edit */
/* do not edit */ export interface ListenerClient {
/* do not edit */     canBeFlashed: boolean;
/* do not edit */     canBeReassigned: boolean;
/* do not edit */     datetime_connected: number;
/* do not edit */     datetime_inactive: number;
/* do not edit */     deviceId: string;
/* do not edit */     id: string;
/* do not edit */     inactive: boolean;
/* do not edit */     ipAddress: string;
/* do not edit */     listenerType: string;
/* do not edit */     socketId: string;
/* do not edit */     cloudConnection: boolean;
/* do not edit */     // volatile
/* do not edit */     device?: Device;
/* do not edit */ }