
/*    +-----------------------------------------------------------------------+    */
/*    |    Do not edit this file directly.                                    |    */
/*    |    It was copied by redundancyJS.                                     |    */
/*    |    To modify it, first edit the source file (see redundancy.json).    |    */
/*    |    Then, run "npx redundancyjs" in the terminal.                      |    */
/*    +-----------------------------------------------------------------------+    */

/* do not edit */ export interface LogItem {
/* do not edit */     datetime: string;
/* do not edit */     log: string;
/* do not edit */     type: "info" | "info-quiet" | "error" | "console_action";
/* do not edit */ }