
/*    +-----------------------------------------------------------------------+    */
/*    |    Do not edit this file directly.                                    |    */
/*    |    It was copied by redundancyJS.                                     |    */
/*    |    To modify it, first edit the source file (see redundancy.json).    |    */
/*    |    Then, run "npx redundancyjs" in the terminal.                      |    */
/*    +-----------------------------------------------------------------------+    */

/* do not edit */ export interface OutputType {
/* do not edit */     enabled: boolean;
/* do not edit */     id: string;
/* do not edit */     label: string;
/* do not edit */     type: string;
/* do not edit */ }