
/*    +-----------------------------------------------------------------------+    */
/*    |    Do not edit this file directly.                                    |    */
/*    |    It was copied by redundancyJS.                                     |    */
/*    |    To modify it, first edit the source file (see redundancy.json).    |    */
/*    |    Then, run "npx redundancyjs" in the terminal.                      |    */
/*    +-----------------------------------------------------------------------+    */

/* do not edit */ export interface SourceTypeDataFields {
/* do not edit */     sourceTypeId: string;
/* do not edit */     fields: {
/* do not edit */         fieldLabel: string;
/* do not edit */         fieldName: string;
/* do not edit */         fieldType: "text" | "port" | "number" | "dropdown" | "info" | "multiselect";
/* do not edit */         options?: {
/* do not edit */             id: string;
/* do not edit */             label: string;
/* do not edit */         }[];
/* do not edit */         text?: string;
/* do not edit */     }[];
/* do not edit */ }