
/*    +-----------------------------------------------------------------------+    */
/*    |    Do not edit this file directly.                                    |    */
/*    |    It was copied by redundancyJS.                                     |    */
/*    |    To modify it, first edit the source file (see redundancy.json).    |    */
/*    |    Then, run "npx redundancyjs" in the terminal.                      |    */
/*    +-----------------------------------------------------------------------+    */

/* do not edit */ export interface SourceTypeBusOptions {
/* do not edit */     sourceTypeId: string;
/* do not edit */     busses: {
/* do not edit */         bus: string;
/* do not edit */         name: string;
/* do not edit */     }[];
/* do not edit */ }