
/*    +-----------------------------------------------------------------------+    */
/*    |    Do not edit this file directly.                                    |    */
/*    |    It was copied by redundancyJS.                                     |    */
/*    |    To modify it, first edit the source file (see redundancy.json).    |    */
/*    |    Then, run "npx redundancyjs" in the terminal.                      |    */
/*    +-----------------------------------------------------------------------+    */

/* do not edit */ export type AddressTallyData = {
/* do not edit */     [address: string]: string[];
/* do not edit */ }
/* do not edit */ 
/* do not edit */ export type SourceTallyData = {
/* do not edit */     [sourceId: string]: string[];
/* do not edit */ }
/* do not edit */ 
/* do not edit */ export type DeviceTallyData = {
/* do not edit */     [deviceId: string]: string[];
/* do not edit */ }