
/*    +-----------------------------------------------------------------------+    */
/*    |    Do not edit this file directly.                                    |    */
/*    |    It was copied by redundancyJS.                                     |    */
/*    |    To modify it, first edit the source file (see redundancy.json).    |    */
/*    |    Then, run "npx redundancyjs" in the terminal.                      |    */
/*    +-----------------------------------------------------------------------+    */

/* do not edit */ export interface TSLTallyData {
/* do not edit */     address: string;
/* do not edit */     label: string;
/* do not edit */     sourceId: string;
/* do not edit */     tally1: number;
/* do not edit */     tally2: number;
/* do not edit */     tally3: number;
/* do not edit */     tally4: number;
/* do not edit */ }