// based on https://stackoverflow.com/a/42199863

const { writeFileSync } = require('fs')
const { promisify } = require('util')
const { exec } = require('child_process')
const exec_promise = promisify(exec)

async function git(cmd, fallback) {
	try {
		const result = await exec_promise(cmd)
		return result.stdout.toString().trim() || fallback
	} catch {
		return fallback
	}
}

async function createVersionsFile(filename) {
	const revision = await git('git rev-parse --short HEAD', process.env.APP_VERSION || 'docker')
	const branch = await git('git rev-parse --abbrev-ref HEAD', 'docker')
	const remote_url = await git('git config --get remote.origin.url', 'https://github.com/josephdadams/TallyArbiter.git')

	console.log(`revision: '${revision}', branch: '${branch}', remote_url: '${remote_url}'`)

	const content = `// this file is automatically generated by git.version.js script
export const versions = {
  revision: '${revision}',
  branch: '${branch}',
  remote_url: '${remote_url}'
};`

	writeFileSync(filename, content, { encoding: 'utf8' })
}

createVersionsFile('src/environments/versions.ts')